### ISSUE TITLE
add a license to the package

### ISSUE THREAD

**Issue by shiftkey** [kevinzwhuang/react-to-string#3]
<img width="389" alt="screen shot 2018-10-30 at 12 08 39 pm" src="https://user-images.githubusercontent.com/359239/47728191-9c1b8d80-dc3c-11e8-8f38-15a2e160bd00.png">

Without a license it's not clear how or where I can use the code

**Comment by kevinzwhuang** [comment]
@shiftkey Thanks for the heads up about this!
I've added the MIT license and released 0.1.1 with the license.

See this commit: https://github.com/kevinzwhuang/react-to-string/commit/a1d03e7099971135331039572449cfdd6f67189f
